app:
  name: inventory-lookup
  type: web
  team: inventory-tools
  slack: "#inventory-lookup-support"
  oncall: inventory-tools-oncall

deploy:
  type: kubernetes
  region: us-west-1
  environment:
    - production
    - staging

security:
  auth:
    type: sso
    provider: square-sso
  roles:
    - inventory-lookup-user
    - inventory-lookup-admin

monitoring:
  type: datadog
  alerts:
    - type: error_rate
      threshold: 1%
    - type: latency
      threshold: 500ms

compliance:
  data:
    classification: internal
    retention: 90days
